apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}
    spec:
      containers:
      - name: node
        image: "{{ .Values.image.repository }}:{{ pluck .Values.global.env .Values.image.tag | first | default .Values.image.tag._default }}"
        pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0
            memory: 256Mi
          limits:
            cpu: 0
            memory: 512Mi
        ports:
        - containerPort: {{ pluck .Values.global.env .Values.app.api.rest_port | first | default .Values.app.api.rest_port._default }}
          name: http
          protocol: TCP

