apiVersion: v1
kind: Service
metadata:
  name: {{ include "pilot-app.fullname" . }}
  labels:
{{ include "pilot-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ pluck .Values.global.env .Values.service.exposePort | first | default .Values.service.exposePort._default }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pilot-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
